server:
  port: 8083
  tomcat:
    max-connections: 50000
    max-threads: 1024
    min-spare-threads: 1024
    accept-count: 1024

logging:
  level:
    ROOT: INFO
    ccom.exercise.movie: INFO
    org.springframework: INFO
    com.zaxxer: INFO

spring:
  profiles:
    active: prod

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/moviedb
    username: root
    password:
    hikari:
      poolName: Hikari
      auto-commit: false
      maximumPoolSize: 20
      connectionTimeout: 30000
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true

  jpa:
    generate-ddl: true
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: 'create-drop'
      jdbc.batch_size: 30
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_second_level_cache: true
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false



app:
  cache:
    ehcache:
      time-to-live-seconds: 3600
      max-entries: 1000