server:
  port: 8080

logging:
  level:
    ROOT: INFO
    ccom.exercise.movie: INFO
    org.springframework: INFO
    com.zaxxer: INFO

spring:
  profiles:
    active: prod

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/moviedb
    username: root
    password:
    hikari:
      poolName: Hikari
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true

  jpa:
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none
      jdbc.batch_size: 30
