logging:
  level:
    ROOT: INFO
    com.onixnet.broadcom: INFO

spring:
  application:
    name: Movie
  # Either way, it can be overridden by `--spring.profiles.active` value passed in the commandline or `-Dspring.profiles.active` set in `JAVA_OPTS`
  profiles:
    active: @spring.profiles.active@
  mvc:
    favicon:
      enabled: false
  jpa:
    open-in-view: false
    properties:
      hibernate.jdbc.time_zone: UTC
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
  data:
    rest:
      basePath: "/api/v1"

application:
  #  CORS id enabled by default for 'local' profile
  cors:
    allowed-origins: "*"
    allowed-methods: "*"
    allowed-headers: "*"
    allow-credentials: true
    max-age-secs: 3600
