server:
  port: 9080

logging:
  level:
    ROOT: INFO
    ccom.exercise.movie: DEBUG
    org.springframework: INFO
    com.zaxxer: DEBUG

spring:
  profiles:
    active: dev

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/moviedb_dev?createDatabaseIfNotExist=true
    username: root
    password: mysql
    hikari:
      poolName: Hikari
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true

  jpa:
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: 'create'
      jdbc.batch_size: 30
