server:
  port: 9080

logging:
  level:
    ROOT: DEBUG
    ccom.exercise.movie: DEBUG
    com.zaxxer: DEBUG

spring:
  profiles:
    active: local

  h2:
    console:
      enabled: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./target/h2db/db/moviedb_local;DB_CLOSE_DELAY=-1
#    url: jdbc:h2:mem:moviedb_local;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MULTI_THREADED=FALSE
    name:
    username: moviedb_local
    password:
    hikari:
      poolName: Hikari
      auto-commit: false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: H2
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: 'create-drop'

