version: '2'
services:
  portfolio-app:
    image: movie
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mariadb://movie-mariadb:3306/moviedb
    ports:
      - 8080:8080
  movie-mariadb:
    extends:
      file: mariadb.yml
      service: portfolio-mariadb
